version: "3"

services:

  nginx:
    image: ${DOCKER_ACC}/nginx
    build: 
      context: ./client
    env_file:
      - ./server/.env
    depends_on:
      - web
      - api
    restart: always
    networks:
      - mern-network
    ports:
      - "80:80"
    volumes:
      # - /client/build/:/usr/share/nginx/html/
      - ./nginx/conf.d:/etc/nginx/conf.d

  web:
    image: ${DOCKER_ACC}/web
    build: ./client
    env_file:
      - ./server/.env
    ports:
      - 5001:3000
    networks:
      - mern-network
    depends_on:
      - api
  api:
    image: ${DOCKER_ACC}/api
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - 5000:3001
    networks:
      - mern-network
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27016:27017
    networks:
      - mern-network
    env_file:
      - ./server/.env
    volumes:
      - database:/data/db

networks:
  mern-network:

volumes:
  database: